name: Frontend - Build and Push Image (Digest)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'package.json'
      - 'angular.json'
      - 'src/**'

env:
  AZURE_ACR_NAME: ${{ vars.AZURE_ACR_NAME }}
  AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
  IMAGE_REPO: raptor/frontend-${{ vars.AZURE_ENV_NAME }}
  INFRA_REPO: arif-md/rap-infra

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR Login
        run: az acr login -n "$AZURE_ACR_NAME"

      - name: Set image tag
        id: meta
        run: echo "tag=${GITHUB_SHA::12}" >> $GITHUB_OUTPUT

      - name: Build and push image (tag)
        run: |
          REGISTRY="${AZURE_ACR_NAME}.azurecr.io"
          REPO="${IMAGE_REPO}"
          TAG="${{ steps.meta.outputs.tag }}"
          IMAGE="$REGISTRY/$REPO:$TAG"
          echo "Building $IMAGE"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Resolve image digest from ACR
        id: digest
        run: |
          REGISTRY="${AZURE_ACR_NAME}.azurecr.io"
          REPO="${IMAGE_REPO}"
          TAG="${{ steps.meta.outputs.tag }}"
          DIGEST=$(az acr repository show-manifests -n "$AZURE_ACR_NAME" --repository "$REPO" --query "[?tags[?@=='$TAG']].digest" -o tsv)
          if [ -z "$DIGEST" ]; then echo "Failed to resolve digest for $REPO:$TAG"; exit 1; fi
          IMAGE_BY_DIGEST="$REGISTRY/$REPO@sha256:$DIGEST"
          echo "image=$IMAGE_BY_DIGEST" >> $GITHUB_OUTPUT

      - name: Dispatch to infra repo with image digest
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT_REPO_DISPATCH }}
          repository: ${{ env.INFRA_REPO }}
          event-type: frontend-image-pushed
          client-payload: |
            {"image": "${{ steps.digest.outputs.image }}"}
